version: '0.1.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./CryptoGramBot/CryptoGramBot.csproj --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish --configuration release ./CryptoGramBot/CryptoGramBot.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: '\CryptoGramBot\bin\Release\netcoreapp2.0\publish'
   name: CryptoGramBot-v$(appveyor_build_version)
   type: FolderProfile
clone_depth: 1
on_finish :
  # any cleanup in here
deploy:
  release: CryptoGramBot-v$(appveyor_build_version)
  description: 'Fix partial buy calculations. Change to web app to improve performance. Try fix non BTC trading. NOTE: two new properties will have to be added in appsettings.json, ServerUrls and TradingCurrency'
  provider: GitHub
  auth_token:
    secure: rMxVtVrce2Oh6Jf2V6c2FDAyJR4/L0ZFpxGl0ntx0g3cHwcqQvWvD4AW0VfIwFBs # your encrypted token from GitHub
  artifact: /.*\.zip/            # upload all zip packages to release assets
  draft: false
  prerelease: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: false
